apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-assistant-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-assistant-pod
  template:
    metadata:
      labels:
        app: ai-assistant-pod
    spec:
      containers:
        - name: ai-assistant-container
          image: gcr.io/PROJECT_ID/IMAGE:TAG  # must use a linux/amd64 image
          ports:
            - containerPort: 80
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-assistant-secret
                  key: OPENAI_API_KEY
            - name: ASSISTANT_ID
              valueFrom:
                secretKeyRef:
                  name: ai-assistant-secret
                  key: ASSISTANT_ID
              
