apiVersion: v1
kind: Service
metadata:
  name: ai-assistant-service
spec:
  type: LoadBalancer
  selector:
    app: ai-assistant-pod
  ports:
  - port: 80 # Service IP Port
    targetPort: 80 # Container Port
     
